using System.Text;
using Leviathan.Server.Apps.Scheduling.Domain;
using Leviathan.Server.Apps.Scheduling.Engine;
using Leviathan.Server.Apps.Scheduling.Storage;
using Leviathan.Server.Apps.Scheduling.Runtime;
using Leviathan.Server.Platform.Apps;
using Leviathan.Server.Platform.Capabilities;
using Leviathan.Server.Platform.Identity;

namespace Leviathan.Server.Apps.Scheduling.Api;

public static class SchedulingEndpoints
{
    public static IEndpointRouteBuilder MapSchedulingEndpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/apps/scheduling");
        static IResult BadTz(string tz) => Results.BadRequest(new SchedulingError("invalid_timezone", $"Invalid IANA timezone id '{tz}'."));
        static IResult Persist() => Results.Problem("Scheduling persistence is unavailable or corrupt; booking truth was not changed.", statusCode: 503, title: "scheduling_persistence_unavailable");

        group.MapGet("/providers", async (SchedulingStore store, ILeviathanRequestContextAccessor ctx, ILeviathanCapabilityPolicy policy, HttpResponse res) => { var c = ctx.Current; var denied = await CapabilityDenied(c, policy, "providers.list", null, null); if (denied is not null) return denied; MarkUnsafe(res); return Results.Ok((await store.GetProviders()).Select(p => EnsureOwnership(p, c!)).Where(p => OwnedBy(p, c!))); });
        group.MapPost("/providers", async (CreateProviderRequest req, SchedulingStore store, ILeviathanRequestContextAccessor ctx, LeviathanLocalDevAppInstallations installs, ILeviathanCapabilityPolicy policy, HttpResponse res) => { var c = ctx.Current; var denied = await CapabilityDenied(c, policy, "providers.create", "provider", req.Slug); if (denied is not null) return denied; if (!SchedulingTimeZone.TryFind(req.TimeZoneId, out _)) return BadTz(req.TimeZoneId); MarkUnsafe(res); var now = DateTimeOffset.UtcNow; var p = new Provider(ProviderId.New(), req.Slug, req.DisplayName, req.TimeZoneId, req.ContactEmail, req.PublicDescription, now, now, c!.AccountId.Value, installs.Scheduling.AppInstallationId.Value); await store.SaveProvider(p); return Results.Ok(p); });
        group.MapGet("/providers/{providerId}", async (string providerId, SchedulingStore store, ILeviathanRequestContextAccessor ctx, ILeviathanCapabilityPolicy policy, HttpResponse res) => { var c = ctx.Current; var denied = await CapabilityDenied(c, policy, "providers.fetch", "provider", providerId); if (denied is not null) return denied; MarkUnsafe(res); var p = await OwnedProvider(store, new(providerId), c!); return p is { } ? Results.Ok(p) : Results.NotFound(new SchedulingError("not_found", "Provider not found.")); });
        group.MapPost("/resources", async (CreateResourceRequest req, SchedulingStore store, ILeviathanRequestContextAccessor ctx, ILeviathanCapabilityPolicy policy, HttpResponse res) => { var c = ctx.Current; var denied = await CapabilityDenied(c, policy, "resources.create", "provider", req.ProviderId); if (denied is not null) return denied; var p = await OwnedProvider(store, new(req.ProviderId), c!); if (p is null) return Results.NotFound(new SchedulingError("not_found", "Provider not found.")); var tz = req.TimeZoneId ?? p.TimeZoneId; if (!SchedulingTimeZone.TryFind(tz, out _)) return BadTz(tz); MarkUnsafe(res); var r = new BookableResource(ResourceId.New(), p.Id, req.DisplayName, req.ResourceType, tz, "Exclusive", true, DateTimeOffset.UtcNow); await store.SaveResource(r); return Results.Ok(r); });
        group.MapPost("/services", async (CreateServiceRequest req, SchedulingStore store, ILeviathanRequestContextAccessor ctx, ILeviathanCapabilityPolicy policy, HttpResponse res) => { var c = ctx.Current; var denied = await CapabilityDenied(c, policy, "services.create", "provider", req.ProviderId); if (denied is not null) return denied; var p = await OwnedProvider(store, new(req.ProviderId), c!); if (p is null) return Results.NotFound(new SchedulingError("not_found", "Provider not found.")); MarkUnsafe(res); var s = new SchedulingService(ServiceId.New(), p.Id, req.Name, req.Description, req.DurationMinutes, req.BufferBeforeMinutes, req.BufferAfterMinutes, [], req.IsPublic, DateTimeOffset.UtcNow); await store.SaveService(s); return Results.Ok(s); });
        group.MapPost("/services/{serviceId}/resources", async (string serviceId, AssignResourceRequest req, SchedulingStore store, ILeviathanRequestContextAccessor ctx, ILeviathanCapabilityPolicy policy, HttpResponse res) => { var c = ctx.Current; var denied = await CapabilityDenied(c, policy, "services.assign_resource", "service", serviceId); if (denied is not null) return denied; var s = await store.GetService(new(serviceId)); if (s is null) return Results.NotFound(new SchedulingError("not_found", "Service not found.")); if (await OwnedProvider(store, s.ProviderId, c!) is null) return Results.NotFound(new SchedulingError("not_found", "Provider not found.")); MarkUnsafe(res); var rid = new ResourceId(req.ResourceId); var updated = s with { AssignedResourceIds = s.AssignedResourceIds.Concat([rid]).Distinct().ToArray() }; await store.SaveService(updated); return Results.Ok(updated); });
        group.MapPost("/availability-rules", async (CreateAvailabilityRuleRequest req, SchedulingStore store, ILeviathanRequestContextAccessor ctx, ILeviathanCapabilityPolicy policy, HttpResponse res) => { var c = ctx.Current; var denied = await CapabilityDenied(c, policy, "availability_rules.create", "provider", req.ProviderId); if (denied is not null) return denied; if (await OwnedProvider(store, new(req.ProviderId), c!) is null) return Results.NotFound(new SchedulingError("not_found", "Provider not found.")); if (!SchedulingTimeZone.TryFind(req.TimeZoneId, out _)) return BadTz(req.TimeZoneId); MarkUnsafe(res); var rule = new AvailabilityRule(AvailabilityRuleId.New(), new(req.ProviderId), new(req.ResourceId), req.TimeZoneId, req.DaysOfWeek, TimeOnly.Parse(req.LocalStartTime), TimeOnly.Parse(req.LocalEndTime), req.EffectiveFrom, req.EffectiveUntil, true, DateTimeOffset.UtcNow); await store.SaveAvailabilityRule(rule); return Results.Ok(rule); });
        group.MapGet("/bookings", async (string providerId, SchedulingStore store, ILeviathanRequestContextAccessor ctx, ILeviathanCapabilityPolicy policy, HttpResponse res) => { var c = ctx.Current; var denied = await CapabilityDenied(c, policy, "bookings.list", "provider", providerId); if (denied is not null) return denied; if (await OwnedProvider(store, new(providerId), c!) is null) return Results.NotFound(new SchedulingError("not_found", "Provider not found.")); MarkUnsafe(res); return Results.Ok(await store.GetBookings(new(providerId))); });
        group.MapGet("/public/{providerSlug}", async (string providerSlug, SchedulingStore store) => await store.GetProviderBySlug(providerSlug) is { } p ? Results.Ok(p) : Results.NotFound(new SchedulingError("not_found", "Provider not found.")));
        group.MapGet("/public/{providerSlug}/services", async (string providerSlug, SchedulingStore store) => await store.GetProviderBySlug(providerSlug) is { } p ? Results.Ok((await store.GetServices(p.Id)).Where(s => s.IsPublic)) : Results.NotFound(new SchedulingError("not_found", "Provider not found.")));
        group.MapGet("/public/{providerSlug}/slots", async (string providerSlug, string serviceId, DateTimeOffset from, DateTimeOffset to, string? timeZone, SlotGenerator gen) => { try { return Results.Ok(await gen.Generate(providerSlug, new(serviceId), from, to, timeZone)); } catch (ArgumentException) { return BadTz(timeZone ?? ""); } catch (InvalidOperationException ex) { return Results.BadRequest(new SchedulingError("invalid_local_time", ex.Message)); } catch (SchedulingPersistenceException) { return Persist(); } });
        group.MapPost("/holds", async (CreateHoldRequest req, BookingClaimService claims) => { if (!SchedulingTimeZone.TryFind(req.TimeZoneId, out _)) return BadTz(req.TimeZoneId); try { var (hold, error) = await claims.CreateHold(new(req.ProviderId), new(req.ServiceId), new(req.ResourceId), new(req.StartsAtUtc, req.EndsAtUtc, req.TimeZoneId)); return hold is null ? Conflict(error!) : Results.Ok(new HoldResponse(hold.Id.Value, hold.ClaimToken, hold.ExpiresAt, hold.Status)); } catch (SchedulingPersistenceException) { return Persist(); } });
        group.MapPost("/holds/{holdId}/intake", async (string holdId, SubmitIntakeRequest req, BookingClaimService claims) => { try { var (hold, error) = await claims.SubmitIntake(new(holdId), req.ClaimToken, new(req.Name, req.Email, req.Phone, req.Notes)); return hold is null ? Error(error!) : Results.Ok(new HoldResponse(hold.Id.Value, hold.ClaimToken, hold.ExpiresAt, hold.Status)); } catch (SchedulingPersistenceException) { return Persist(); } });
        group.MapPost("/bookings/confirm", async (ConfirmBookingRequest req, BookingClaimService claims) => { try { var (booking, error) = await claims.Confirm(new(req.HoldId), req.ClaimToken, req.Customer); return booking is null ? Error(error!) : Results.Ok(booking); } catch (SchedulingPersistenceException) { return Persist(); } });
        group.MapPost("/bookings/{bookingId}/cancel", async (string bookingId, CancelBookingRequest req, BookingClaimService claims) => { try { var (booking, error, auditEventId, lifecycle) = await claims.Cancel(new(bookingId), req.Reason, req.Message, req.Actor); return booking is null ? Error(error!) : Results.Ok(new CancelBookingResponse(booking, auditEventId!, lifecycle!)); } catch (SchedulingPersistenceException) { return Persist(); } });
        group.MapPost("/bookings/{bookingId}/reschedule/holds", async (string bookingId, CreateReplacementHoldRequest req, BookingClaimService claims, SchedulingBookingRuntime lifecycle) => { if (!SchedulingTimeZone.TryFind(req.TimeZoneId, out _)) return BadTz(req.TimeZoneId); if (!string.IsNullOrWhiteSpace(req.DisplayTimeZoneId) && !SchedulingTimeZone.TryFind(req.DisplayTimeZoneId, out _)) return BadTz(req.DisplayTimeZoneId!); try { var range = new ZonedTimeRange(req.StartUtc, req.EndUtc, req.TimeZoneId); var (hold, error, auditEventId) = await claims.CreateReplacementHold(new(bookingId), new(req.ServiceId), new(req.ResourceId), range, req.Reason, req.Message, req.Actor); if (hold is null) return Error(error!); var displayZone = req.DisplayTimeZoneId ?? req.TimeZoneId; var display = SchedulingTimeZone.Display(range, displayZone); var slot = new BookableSlotDto(hold.ProviderId.Value, hold.ServiceId.Value, hold.ResourceId.Value, hold.Range.StartsAtUtc, hold.Range.EndsAtUtc, hold.Range.TimeZoneId, $"{display.LocalStart} – {display.LocalEnd}", hold.Range.TimeZoneId, displayZone, display.LocalStart, display.LocalEnd); return Results.Ok(new ReplacementHoldResponse(bookingId, hold.Id.Value, hold.ClaimToken, slot, auditEventId, lifecycle.ReadByHold(hold.ProviderId, hold.Id))); } catch (SchedulingPersistenceException) { return Persist(); } });
        group.MapGet("/bookings/{bookingId}", async (string bookingId, SchedulingStore store) => await store.GetBooking(new(bookingId)) is { } b ? Results.Ok(b) : Results.NotFound(new SchedulingError("not_found", "Booking not found.")));
        group.MapGet("/bookings/{bookingId}/audit", async (string bookingId, string providerId, SchedulingStore store) => Results.Ok(await store.GetBookingAudit(new(providerId), new(bookingId))));
        group.MapGet("/bookings/{bookingId}/ics", async (string bookingId, SchedulingStore store) => await store.GetBooking(new(bookingId)) is { } b ? b.Status == "confirmed" ? Results.Text(ToIcs(b), "text/calendar", Encoding.UTF8) : Results.BadRequest(new SchedulingError(b.Status == "rescheduled" ? "booking_rescheduled" : "booking_not_confirmed", "Only confirmed bookings can be exported as local ICS events.")) : Results.NotFound(new SchedulingError("not_found", "Booking not found.")));
        group.MapGet("/bookings/{bookingId}/lifecycle", async (string bookingId, SchedulingStore store, SchedulingBookingRuntime lifecycle) => await store.GetBooking(new(bookingId)) is { } b ? lifecycle.ReadByBooking(b.ProviderId, b.Id) is { } summary ? Results.Ok(summary) : Results.NotFound(new SchedulingError("not_found", "Lifecycle checkpoint not found.")) : Results.NotFound(new SchedulingError("not_found", "Booking not found.")));
        group.MapGet("/holds/{holdId}/lifecycle", (string holdId, string providerId, SchedulingBookingRuntime lifecycle) => lifecycle.ReadByHold(new(providerId), new(holdId)) is { } summary ? Results.Ok(summary) : Results.NotFound(new SchedulingError("not_found", "Lifecycle checkpoint not found.")));
        return app;
    }

    private static async Task<IResult?> CapabilityDenied(LeviathanRequestContext? c, ILeviathanCapabilityPolicy policy, string operation, string? targetKind, string? targetId)
    {
        if (c is null) return UnsafeCapability("missing_request_context");
        var decision = await policy.Evaluate(c, new LeviathanCapabilityCheck("scheduling", LeviathanLocalDevAppInstallations.SchedulingInstallationId, new(LeviathanCapabilityNames.AdminProviderConfigure), LeviathanCapabilityScope.Account(), operation, targetKind, targetId, c.RequestId));
        return decision.Allowed ? null : UnsafeCapability(decision.ReasonCode, decision.Audit);
    }
    private static IResult UnsafeCapability(string reason, LeviathanCapabilityAuditEnvelope? audit = null) => Results.Json(new { error = reason == "unsafe_admin_disabled" || reason == "missing_request_context" ? "unsafe_admin_disabled" : "capability_denied", reason, message = reason == "unsafe_admin_disabled" || reason == "missing_request_context" ? "Unsafe Scheduling admin APIs are local-dev only and require LEVIATHAN_ALLOW_UNSAFE_ADMIN=true. Do not expose this mode publicly." : "Scheduling admin capability admin.provider.configure is not granted for this local account/app installation.", audit }, statusCode: StatusCodes.Status403Forbidden);
    private static void MarkUnsafe(HttpResponse res) => res.Headers.Append("X-Leviathan-Unsafe-Admin", "local-dev-only");
    private static Provider EnsureOwnership(Provider p, LeviathanRequestContext c) => string.IsNullOrWhiteSpace(p.AccountId) || string.IsNullOrWhiteSpace(p.AppInstallationId) ? p with { AccountId = c.AccountId.Value, AppInstallationId = LeviathanLocalDevAppInstallations.SchedulingInstallationId.Value } : p;
    private static bool OwnedBy(Provider p, LeviathanRequestContext c) => p.AccountId == c.AccountId.Value && p.AppInstallationId == LeviathanLocalDevAppInstallations.SchedulingInstallationId.Value;
    private static async Task<Provider?> OwnedProvider(SchedulingStore store, ProviderId id, LeviathanRequestContext c)
    {
        var p = await store.GetProvider(id);
        return p is null ? null : OwnedBy(EnsureOwnership(p, c), c) ? EnsureOwnership(p, c) : null;
    }
    private static string ToIcs(Booking b) => $"BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Leviathan//Scheduling//EN\r\nBEGIN:VEVENT\r\nUID:{b.Id.Value}@leviathan.local\r\nDTSTAMP:{DateTimeOffset.UtcNow:yyyyMMdd'T'HHmmss'Z'}\r\nDTSTART:{b.Range.StartsAtUtc:yyyyMMdd'T'HHmmss'Z'}\r\nDTEND:{b.Range.EndsAtUtc:yyyyMMdd'T'HHmmss'Z'}\r\nSUMMARY:Booking\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n";
    private static IResult Conflict(string error) => Results.Conflict(new SchedulingError(error, "The requested exclusive resource interval is no longer available."));
    private static IResult Error(string error) => error is "slot_conflict" ? Conflict(error) : error is "not_found" ? Results.NotFound(new SchedulingError(error, "Booking not found.")) : error is "booking_not_cancellable" ? Results.Conflict(new SchedulingError(error, "Only confirmed bookings can be cancelled by the M11 policy.")) : error is "booking_not_reschedulable" ? Results.Conflict(new SchedulingError(error, "Only confirmed bookings can be rescheduled by the M19 policy.")) : Results.BadRequest(new SchedulingError(error, "The scheduling request could not be completed."));
}
