// Stable landmark map for the scheduling app (machinalayout/atlas). "Keep
// the file. Add the map." - most of the app is still one large views.tsx/
// layouts.ts, same as before M0; the setup wizard is the one surface that's
// actually moved into its own directory so far. This atlas describes both:
// where things live today, and where the still-in-progress split lands
// each surface (per the M0-M4 milestone ladder), so re-deriving "where does
// X live" doesn't mean re-reading 3,000+ lines cold, for either a person or
// a model. Update this file as each later milestone lands its own surface.

import { defineMachinaAtlas } from "machinalayout/atlas";

export const SchedulingAtlas = defineMachinaAtlas({
  app: "Scheduling",
  notes:
    "Second app on the Leviathan platform (Ariadne is first). M0 rewrote the provider setup wizard with a real DeusMachina-backed live orchestrator. M1 moved landing and the bookings list into their own directories (structural + dead-row cleanup only). M2 moved confirmation + reschedule together (they share a screen - reschedule is an action reachable from confirmation, not a separate flow) and gave reschedule a real DeusMachina port, now split across a stage machine (available/picker/replacement/result) plus five independent machinalayout/async task controllers for the network steps - a cleaner split than M0's setup port could manage, since machinalayout/async didn't exist yet when M0 was built. Public booking flow is the only surface still inside views.tsx/layouts.ts, pending M3 (deliberately last).",
  sections: [
    {
      key: "setup",
      name: "Provider setup wizard",
      kind: "page",
      route: "/apps/scheduling/setup",
      fixture: "provider-setup",
      owns: [
        "ProviderSetupFlow",
        "ProviderSetupView",
        "LiveProviderSetupView",
        "SetupChecklist",
        "SetupEntitySummary",
        "SetupResultCard",
        "SetupSectionCard",
        "SetupProgressBadge",
        "setupStepState",
        "createDefaultSetupDraft",
        "setupEntitiesFromValues",
        "createSetupMachine",
        "createProviderTask",
        "createResourceTask",
        "createServiceTask",
        "createAvailabilityTask",
      ],
      uses: ["shared/format", "shared/liveContext", "shared/AdminGateBanner", "machina/useAsyncTask"],
      usedBy: ["shared-shell"],
      tags: ["scheduling", "setup", "m0", "deusmachina", "async", "m2.5"],
      notes:
        "M0 deliverable, M2.5 follow-up. Real DeusMachina port (Candidate 1 from the DeusMachina port audit) - see setup/setupMachine.ts. Fixture (ProviderSetupView) and live (LiveProviderSetupView) modes render the same ProviderSetupFlow component tree, driven by different event sources; that sharing is what makes the fixture/live unification flagged in the port audit tractable once every surface follows this pattern. M2.5 replaced runStep's four manual try/catch blocks with AsyncTaskControllers (setup/setupTasks.ts) - the Deus stage machine's *Pending states were deliberately left unchanged, since they gate step eligibility (createResource only eligible from idle), a different job than AsyncTaskController's per-call lifecycle tracking.",
    },
    {
      key: "shared-format",
      name: "Shared formatters",
      kind: "shared",
      file: "shared/format.ts",
      owns: ["slotKey", "statusLabel", "formatDateTimeRange", "buildAvailableDates", "chipToneForValue"],
      usedBy: ["setup", "landing", "public-booking", "confirmation", "bookings"],
      tags: ["shared", "pure"],
      notes: "Pure, no React. Extracted from views.tsx before the setup rewrite - was always self-contained, just trapped behind every other import in one file.",
    },
    {
      key: "shared-live-context",
      name: "Live-mode routing & admin gate",
      kind: "shared",
      file: "shared/liveContext.ts",
      owns: ["isFixtureMode", "loadLiveContext", "saveLiveContext", "isUnsafeAdminError", "controlledSchedulingError"],
      usedBy: ["setup", "landing", "public-booking", "confirmation", "bookings"],
      tags: ["shared", "live-mode"],
      notes:
        "Extracted specifically to avoid a circular import between views.tsx and setup/ (both need these helpers; only one of them could keep them without the other importing back). Same boundary the original scheduling-app restructuring audit already recommended.",
    },
    {
      key: "shared-admin-gate-banner",
      name: "Admin gate / ownership banners",
      kind: "shared",
      file: "shared/AdminGateBanner.tsx",
      owns: ["AdminModeBanner", "OwnershipSummary"],
      usedBy: ["setup", "confirmation", "front-page", "bookings"],
      tags: ["shared", "presentational"],
    },
    {
      key: "shared-status-chip",
      name: "Status badge",
      kind: "shared",
      file: "shared/StatusChip.tsx",
      owns: ["StatusChip"],
      usedBy: ["bookings", "confirmation", "public-booking", "shared-booking-meta-panels"],
      tags: ["shared", "presentational", "m1"],
      notes: "Extracted in M1 - used by bookings and confirmation both, so it couldn't stay wherever it was first touched.",
    },
    {
      key: "shared-booking-meta-panels",
      name: "Payment/notification summary panels",
      kind: "shared",
      file: "shared/BookingMetaPanels.tsx",
      owns: ["BookingMetaPanels", "NotificationSummaryList"],
      uses: ["shared-status-chip", "shared-format"],
      usedBy: ["bookings", "confirmation"],
      tags: ["shared", "presentational", "m1"],
    },
    {
      key: "shared-booking-status-summary",
      name: "Compact booking status summary",
      kind: "shared",
      file: "shared/BookingStatusSummary.tsx",
      owns: ["BookingStatusSummary"],
      uses: ["shared-booking-meta-panels", "shared-status-chip"],
      usedBy: ["shared-shell"],
      tags: ["shared", "presentational", "m2"],
      notes:
        "Extracted in M2 for the now-deleted PublicBookingFlowView (a public-booking usage) and the confirmation surface - the confirmation usage never actually shipped (ConfirmationView built its own inline summary instead), and PublicBookingFlowView was deleted in M3 as unreachable dead code. Its one real usage today is SchedulingSidebarView's generic \"fixture spotlight\" section, shared across every surface, not booking-specific. Corrected here rather than left stale.",
    },
    {
      key: "front-page",
      name: "Front page / landing",
      kind: "page",
      route: "/apps/scheduling",
      fixture: "landing",
      owns: ["SchedulingHomeView", "LiveSchedulingLandingView"],
      uses: ["shared/format", "shared/liveContext", "shared/AdminGateBanner"],
      usedBy: ["shared-shell"],
      tags: ["scheduling", "landing", "m1"],
      notes: "M1 deliverable. Pure relocate - no orchestration to port, layouts.ts's fallback branch was already a single clean row before this milestone.",
    },
    {
      key: "public-booking",
      name: "Public booking flow",
      kind: "page",
      route: "/book/:providerSlug",
      fixture: "public-booking",
      owns: [
        "SchedulingBookingPageProvider",
        "useBookingPage",
        "createPublicBookingMachine",
        "loadProviderAndServicesTask",
        "listPublicSlotsTask",
        "createPublicHoldTask",
        "submitPublicIntakeTask",
        "satisfyPublicPaymentTask",
        "confirmPublicBookingTask",
        "BookingHeaderView",
        "BookingSummaryPanelView",
        "BookingMainHeaderView",
        "BookingCalendarRegionView",
        "BookingSlotsRegionView",
        "BookingFooterSummaryView",
      ],
      uses: ["shared/format", "shared/liveContext", "machina/useAsyncTask"],
      usedBy: ["shared-shell"],
      tags: ["scheduling", "booking", "m3", "deusmachina", "async"],
      notes:
        "M3 deliverable, saved for last on purpose (highest value, highest risk, deepest fixture/live divergence). Real finding while building this: PublicBookingFlowView, LivePublicBookingView, and SlotPickerView (the pre-M3 components) were entirely unreachable dead code, not a live double-fetch bug as first suspected - the booking surface's layout never assigns a \"schedulingMain\" view, it has its own dedicated slot set (bookingHeader, bookingSummaryPanel, bookingCalendarRegion, etc.), each independently registered and already consuming useBookingPage() directly in both fixture and live mode. Deleted all three rather than porting them. BookingPageContextValue's field shape kept identical to before, so the ~20 presentational components downstream needed zero changes - only SchedulingBookingPageProvider's internals changed, from ~15 useState calls plus a shared busy string to a real stage machine (browsing/held/confirmed) plus six independent AsyncTaskControllers. Fixture mode here is genuinely interactive (selecting a slot synthesizes a fixture hold synchronously) unlike reschedule's static-preview fixture mode, so `live` lives on the board itself - a couple of transitions (selectDate, clearSelection) genuinely behave differently in live vs fixture and Deus transitions only see (board, event), not surrounding component state.",
    },
    {
      key: "confirmation",
      name: "Booking confirmation & reschedule",
      kind: "page",
      route: "/book/:providerSlug/confirmed/:bookingId",
      fixture: "booking-confirmation",
      owns: [
        "ConfirmationView",
        "ConfirmationSurfaceView",
        "LiveConfirmationView",
        "BookingReschedulePanel",
        "createRescheduleMachine",
        "listReplacementSlotsTask",
        "createReplacementHoldTask",
        "submitReplacementIntakeTask",
        "satisfyReplacementPaymentTask",
        "confirmReplacementTask",
        "getBookingForConfirmationTask",
      ],
      uses: ["shared/format", "shared/liveContext", "shared/AdminGateBanner", "shared/StatusChip", "shared/BookingMetaPanels", "machina/useAsyncTask"],
      usedBy: ["shared-shell", "bookings"],
      tags: ["scheduling", "confirmation", "reschedule", "m2", "deusmachina", "async", "m2.5"],
      notes:
        "M2 deliverable, M2.5 follow-up. Confirmation and reschedule moved together deliberately - reschedule is an action reachable from the confirmation screen (and from the bookings list - see bookings.notes), not a separate flow, so they share a directory even though BookingReschedulePanel is its own file. The reschedule stage machine (available/picker/replacement/result) governs macro stage only; each network step (list slots, create hold, submit intake, satisfy payment, confirm) runs through its own machinalayout/async AsyncTaskController via the shared machina/useAsyncTask hook. Fixture-mode rendering reads `stage` directly from the fixture prop rather than the machine's own graph state, since `createDeusSnapshot` always starts at `machine.initial` regardless of board data and `renderToStaticMarkup` never runs the effect that would otherwise sync it - board data is seeded correctly on first paint via `boardFromFixtureState` instead. M2.5 ported LiveConfirmationView's own booking-fetch-on-mount to useAsyncTask too (confirmationTasks.ts), closing the TODO M2 left.",
    },
    {
      key: "bookings",
      name: "Provider bookings list",
      kind: "page",
      route: "/apps/scheduling/bookings",
      fixture: "notification-summary",
      owns: ["ProviderBookingsView", "LiveProviderBookingsView", "BookingDebugPanel", "listBookingsTask", "loadBookingDetailTask", "cancelBookingTask"],
      uses: ["shared/format", "shared/liveContext", "shared/AdminGateBanner", "shared/StatusChip", "shared/BookingMetaPanels", "confirmation", "machina/useAsyncTask"],
      usedBy: ["shared-shell"],
      tags: ["scheduling", "bookings", "m1", "async", "m2.5"],
      notes:
        "M1 deliverable: structural move + dead-row cleanup only (six dead rows removed from layouts.ts's bookings branch, same pattern M0 found in setup). M2.5: refresh/select-detail/cancel now each run through their own AsyncTaskController (bookingsListTasks.ts) instead of one shared `busy` boolean - closes a real gap, not just a cleanup: selecting booking A then quickly selecting booking B now actually cancels A's in-flight detail fetch, so a slow response for A can no longer land after B is already selected and clobber its data.",
    },
    {
      key: "shared-shell",
      name: "Scheduling shell (Machina layout + slots)",
      kind: "shared",
      owns: ["buildSchedulingLayout", "SchedulingHeroView", "SchedulingMainView", "SchedulingSidebarView"],
      usedBy: ["setup", "front-page", "public-booking", "confirmation", "bookings"],
      tags: ["shared", "layout", "shell"],
      notes:
        "layouts.ts's setup (M0), bookings (M1), and confirmation (M2) branches were all rewritten with machinalayout/machina (M.vstack/M.node), each removing a dead-row pattern (~15-40 lines of hand-computed absolute positions for rows that were never actually rendered - no view assigned). The public-booking branch is a different situation, confirmed while building M3: no dead rows (every slot it defines - bookingHeader, bookingSummaryPanel, bookingCalendarRegion, etc. - is genuinely registered and rendered), but it's authored as two entirely separate ~150-line functions (buildPublicBookingHorizontalLayout/VerticalLayout) instead of one row set with M.when variants. Tracked as M3.5, deliberately deferred rather than bundled into M3's state-unification work.",
    },
  ],
});
