// Stable landmark map for the Scheduling app (machinalayout/atlas). Every
// major surface now owns a directory: setup/, landing/, publicBooking/,
// confirmation/, and bookings/; shared/ holds cross-surface presentation
// and live-context helpers. views.tsx is the shell-dispatch layer and
// layouts.ts is the explicit Machina geometry layer. This Atlas describes
// that post-M4 architecture so locating a surface does not require reading
// the shell or layout definitions end-to-end.
//
// M3.5: table-authored via machinalayout/table + Atlas.defineAtlasFromTable
// instead of a hand-written object array. Same data, same runtime Atlas
// shape - the win is cell-level diagnostics. Across M1-M3 I caught and
// fixed several stale notes by hand (M1's bookings section, M2's
// confirmation section, M3's BookingStatusSummary correction) purely
// because I happened to reread this file each time. A malformed cell here
// now fails with a specific `SchedulingAtlas.owns[3]`-style diagnostic
// instead of a silently-wrong runtime object.

import { Atlas } from "machinalayout/atlas";
import { Table } from "machinalayout/table";

const schedulingAtlasTable = Table.defineWithSchema({
  id: "schedulingAtlas",
  schema: Atlas.sectionTableSchema(),
  columns: {
    key: [
      "setup",
      "shared-format",
      "shared-live-context",
      "shared-admin-gate-banner",
      "shared-status-chip",
      "shared-booking-meta-panels",
      "shared-booking-status-summary",
      "front-page",
      "public-booking",
      "confirmation",
      "bookings",
      "shared-shell",
    ],
    name: [
      "Provider setup wizard",
      "Shared formatters",
      "Live-mode routing & admin gate",
      "Admin gate / ownership banners",
      "Status badge",
      "Payment/notification summary panels",
      "Compact booking status summary",
      "Front page / landing",
      "Public booking flow",
      "Booking confirmation & reschedule",
      "Provider bookings list",
      "Scheduling shell (Machina layout + slots)",
    ],
    kind: ["page", "shared", "shared", "shared", "shared", "shared", "shared", "page", "page", "page", "page", "shared"],
    route: [
      "/apps/scheduling/setup",
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      "/apps/scheduling",
      "/book/:providerSlug",
      "/book/:providerSlug/confirmed/:bookingId",
      "/apps/scheduling/bookings",
      undefined,
    ],
    file: [
      "setup/",
      "shared/format.ts",
      "shared/liveContext.ts",
      "shared/AdminGateBanner.tsx",
      "shared/StatusChip.tsx",
      "shared/BookingMetaPanels.tsx",
      "shared/BookingStatusSummary.tsx",
      "landing/",
      "publicBooking/",
      "confirmation/",
      "bookings/",
      "views.tsx; layouts.ts",
    ],
    fixture: [
      "provider-setup",
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      undefined,
      "landing",
      "public-booking",
      "booking-confirmation",
      "notification-summary",
      undefined,
    ],
    owns: [
      [
        "ProviderSetupFlow",
        "ProviderSetupView",
        "LiveProviderSetupView",
        "SetupChecklist",
        "SetupEntitySummary",
        "SetupResultCard",
        "SetupSectionCard",
        "SetupProgressBadge",
        "setupStepState",
        "createDefaultSetupDraft",
        "setupEntitiesFromValues",
        "createSetupMachine",
        "createProviderTask",
        "createResourceTask",
        "createServiceTask",
        "createAvailabilityTask",
      ],
      ["slotKey", "statusLabel", "formatDateTimeRange", "buildAvailableDates", "chipToneForValue"],
      ["isFixtureMode", "loadLiveContext", "saveLiveContext", "isUnsafeAdminError", "controlledSchedulingError"],
      ["AdminModeBanner", "OwnershipSummary"],
      ["StatusChip"],
      ["BookingMetaPanels", "NotificationSummaryList"],
      ["BookingStatusSummary"],
      ["SchedulingHomeView", "LiveSchedulingLandingView"],
      [
        "SchedulingBookingPageProvider",
        "useBookingPage",
        "createPublicBookingMachine",
        "loadProviderAndServicesTask",
        "listPublicSlotsTask",
        "createPublicHoldTask",
        "submitPublicIntakeTask",
        "satisfyPublicPaymentTask",
        "confirmPublicBookingTask",
        "BookingHeaderView",
        "BookingSummaryPanelView",
        "BookingMainHeaderView",
        "BookingCalendarRegionView",
        "BookingSlotsRegionView",
        "BookingFooterSummaryView",
      ],
      [
        "ConfirmationView",
        "ConfirmationSurfaceView",
        "LiveConfirmationView",
        "BookingReschedulePanel",
        "createRescheduleMachine",
        "listReplacementSlotsTask",
        "createReplacementHoldTask",
        "submitReplacementIntakeTask",
        "satisfyReplacementPaymentTask",
        "confirmReplacementTask",
        "getBookingForConfirmationTask",
      ],
      ["ProviderBookingsView", "LiveProviderBookingsView", "BookingDebugPanel", "listBookingsTask", "loadBookingDetailTask", "cancelBookingTask"],
      ["buildSchedulingLayout", "SchedulingHeroView", "SchedulingMainView", "SchedulingSidebarView"],
    ],
    uses: [
      ["shared/format", "shared/liveContext", "shared/AdminGateBanner", "machina/useAsyncTask"],
      [],
      [],
      [],
      [],
      ["shared-status-chip", "shared-format"],
      ["shared-booking-meta-panels", "shared-status-chip"],
      ["shared/format", "shared/liveContext", "shared/AdminGateBanner"],
      ["shared/format", "shared/liveContext", "machina/useAsyncTask"],
      ["shared/format", "shared/liveContext", "shared/AdminGateBanner", "shared/StatusChip", "shared/BookingMetaPanels", "machina/useAsyncTask"],
      ["shared/format", "shared/liveContext", "shared/AdminGateBanner", "shared/StatusChip", "shared/BookingMetaPanels", "confirmation", "machina/useAsyncTask"],
      [],
    ],
    usedBy: [
      ["shared-shell"],
      ["setup", "landing", "public-booking", "confirmation", "bookings"],
      ["setup", "landing", "public-booking", "confirmation", "bookings"],
      ["setup", "confirmation", "front-page", "bookings"],
      ["bookings", "confirmation", "public-booking", "shared-booking-meta-panels"],
      ["bookings", "confirmation"],
      ["shared-shell"],
      ["shared-shell"],
      ["shared-shell"],
      ["shared-shell", "bookings"],
      ["shared-shell"],
      ["setup", "front-page", "public-booking", "confirmation", "bookings"],
    ],
    tags: [
      ["scheduling", "setup", "m0", "deusmachina", "async", "m2.5"],
      ["shared", "pure"],
      ["shared", "live-mode"],
      ["shared", "presentational"],
      ["shared", "presentational", "m1"],
      ["shared", "presentational", "m1"],
      ["shared", "presentational", "m2"],
      ["scheduling", "landing", "m1"],
      ["scheduling", "booking", "m3", "deusmachina", "async"],
      ["scheduling", "confirmation", "reschedule", "m2", "deusmachina", "async", "m2.5"],
      ["scheduling", "bookings", "m1", "async", "m2.5"],
      ["shared", "layout", "shell"],
    ],
    notes: [
      "M0 deliverable, M2.5 follow-up. Real DeusMachina port (Candidate 1 from the DeusMachina port audit) - see setup/setupMachine.ts. Fixture (ProviderSetupView) and live (LiveProviderSetupView) modes render the same ProviderSetupFlow component tree, driven by different event sources; that sharing is what makes the fixture/live unification flagged in the port audit tractable once every surface follows this pattern. M2.5 replaced runStep's four manual try/catch blocks with AsyncTaskControllers (setup/setupTasks.ts) - the Deus stage machine's *Pending states were deliberately left unchanged, since they gate step eligibility (createResource only eligible from idle), a different job than AsyncTaskController's per-call lifecycle tracking. M3.5 replaced the four create-transitions with Deus.pendingResultTransitionsFromTable, the four LiveProviderSetupView buttons with Command.commandsFromTable, and ProviderSetupFlow's provider/resource/service/availability fields with Form.fieldsFromTable.",
      "Pure, no React. Extracted from views.tsx before the setup rewrite - was always self-contained, just trapped behind every other import in one file.",
      "Extracted specifically to avoid a circular import between views.tsx and setup/ (both need these helpers; only one of them could keep them without the other importing back). Same boundary the original scheduling-app restructuring audit already recommended.",
      undefined,
      "Extracted in M1 - used by bookings and confirmation both, so it couldn't stay wherever it was first touched.",
      undefined,
      "Extracted in M2 for the now-deleted PublicBookingFlowView (a public-booking usage) and the confirmation surface - the confirmation usage never actually shipped (ConfirmationView built its own inline summary instead), and PublicBookingFlowView was deleted in M3 as unreachable dead code. Its one real usage today is SchedulingSidebarView's generic \"fixture spotlight\" section, shared across every surface, not booking-specific. Corrected here rather than left stale.",
      "M1 deliverable. Pure relocate - no orchestration to port, layouts.ts's fallback branch was already a single clean row before this milestone.",
      "M3 deliverable, saved for last on purpose (highest value, highest risk, deepest fixture/live divergence). Real finding while building this: PublicBookingFlowView, LivePublicBookingView, and SlotPickerView (the pre-M3 components) were entirely unreachable dead code, not a live double-fetch bug as first suspected - the booking surface's layout never assigns a \"schedulingMain\" view, it has its own dedicated slot set (bookingHeader, bookingSummaryPanel, bookingCalendarRegion, etc.), each independently registered and already consuming useBookingPage() directly in both fixture and live mode. Deleted all three rather than porting them. BookingPageContextValue's field shape kept identical to before, so the ~20 presentational components downstream needed zero changes - only SchedulingBookingPageProvider's internals changed, from ~15 useState calls plus a shared busy string to a real stage machine (browsing/held/confirmed) plus six independent AsyncTaskControllers. Fixture mode here is genuinely interactive (selecting a slot synthesizes a fixture hold synchronously) unlike reschedule's static-preview fixture mode, so `live` lives on the board itself - a couple of transitions (selectDate, clearSelection) genuinely behave differently in live vs fixture and Deus transitions only see (board, event), not surrounding component state.",
      "M2 deliverable, M2.5 follow-up. Confirmation and reschedule moved together deliberately - reschedule is an action reachable from the confirmation screen (and from the bookings list - see bookings.notes), not a separate flow, so they share a directory even though BookingReschedulePanel is its own file. The reschedule stage machine (available/picker/replacement/result) governs macro stage only; each network step (list slots, create hold, submit intake, satisfy payment, confirm) runs through its own machinalayout/async AsyncTaskController via the shared machina/useAsyncTask hook. Fixture-mode rendering reads `stage` directly from the fixture prop rather than the machine's own graph state, since `createDeusSnapshot` always starts at `machine.initial` regardless of board data and `renderToStaticMarkup` never runs the effect that would otherwise sync it - board data is seeded correctly on first paint via `boardFromFixtureState` instead. M2.5 ported LiveConfirmationView's own booking-fetch-on-mount to useAsyncTask too (confirmationTasks.ts), closing the TODO M2 left.",
      "M1 deliverable: structural move + dead-row cleanup only (six dead rows removed from layouts.ts's bookings branch, same pattern M0 found in setup). M2.5: refresh/select-detail/cancel now each run through their own AsyncTaskController (bookingsListTasks.ts) instead of one shared `busy` boolean - closes a real gap, not just a cleanup: selecting booking A then quickly selecting booking B now actually cancels A's in-flight detail fetch, so a slow response for A can no longer land after B is already selected and clobber its data.",
      "layouts.ts's setup (M0), bookings (M1), and confirmation (M2) branches were all rewritten with machinalayout/machina (M.vstack/M.node), each removing a dead-row pattern (~15-40 lines of hand-computed absolute positions for rows that were never actually rendered - no view assigned). The public-booking branch is a different situation, confirmed while building M3: no dead rows (every slot it defines - bookingHeader, bookingSummaryPanel, bookingCalendarRegion, etc. - is genuinely registered and rendered), but it's authored as two entirely separate ~150-line functions (buildPublicBookingHorizontalLayout/VerticalLayout) instead of one row set with M.when variants. M3.5 confirmed full consolidation doesn't actually fit (desktop and mobile render genuinely different registered components, not the same content repositioned) - factored out the shared shell scaffolding instead, left the two content trees separate.",
    ],
  },
});

export const SchedulingAtlas = Atlas.defineAtlasFromTable({
  app: "Scheduling",
  sections: schedulingAtlasTable,
  notes:
    "Second app on the Leviathan platform (Ariadne is first). M0 rewrote the provider setup wizard with a real DeusMachina-backed live orchestrator. M1 moved landing and the bookings list into their own directories (structural + dead-row cleanup only). M2 moved confirmation + reschedule together (they share a screen - reschedule is an action reachable from confirmation, not a separate flow) and gave reschedule a real DeusMachina port, now split across a stage machine (available/picker/replacement/result) plus five independent machinalayout/async task controllers for the network steps - a cleaner split than M0's setup port could manage, since machinalayout/async didn't exist yet when M0 was built. M3 finished the last surface (public booking), finding and deleting ~700 lines of unreachable dead code along the way. M3.5 revisited the public-booking layout split and, separately, table-authored this atlas plus setup's transitions/buttons/form fields via machinalayout/table + Deus/Command/Form's table bridges (0.6.0). M4 (cutover): views.tsx and layouts.ts were NOT deleted - tracing what was actually left in each after M0-M3.5 showed they had already converged into the legitimate shell-dispatch layer (SchedulingHeroView/MainView/SidebarView + their live counterparts) and the layout-definition layer for the whole app, respectively, analogous to src/machina's own views.tsx/layouts.ts for non-scheduling routes - not monolith remnants waiting to be deleted. Did strip ~90 dead imports left over in views.tsx from the deleted booking-flow/setup/confirmation/bookings-list code, and split the two remaining monolithic test describe blocks (views.test.tsx, layouts.test.ts) into per-surface describes matching the directory split. Machine conventions and the fixture/live unification question (revisited with four real examples instead of speculation) are written up in CONVENTIONS.md.",
});
