export type EntityId = { value: string };
export type Provider = { id: EntityId; slug: string; displayName: string; timeZoneId: string; contactEmail?: string; publicDescription?: string; accountId?: string; appInstallationId?: string };
export type LocalDevPlatformContext = { actorKind: "local-dev"; userId: string; accountId: string; unsafeLocalDev: boolean; requestId: string; schedulingInstallation: { appInstallationId: EntityId; accountId: EntityId; appId: string; status: string; persistenceScope: string } };
export type BookableResource = { id: EntityId; providerId: EntityId; displayName: string; resourceType: string; timeZoneId: string };
export type MoneyAmount = { minorUnits: number; currency: string };
export type SchedulingPaymentPolicy = {
  requiresDeposit: boolean;
  requiresPrepay: boolean;
  depositAmount?: MoneyAmount | null;
  prepayAmount?: MoneyAmount | null;
  currency: string;
  paymentTiming: string;
  paymentProviderMode: string;
  cancellationPaymentPolicy: string;
  reschedulePaymentPolicy: string;
};
export type NotificationRule = { trigger: string; channel: string; recipientType: string; templateKey: string; offsetMinutesBeforeStart?: number | null };
export type SchedulingNotificationPolicy = { enabled: boolean; rules: NotificationRule[] };
export type SchedulingService = {
  id: EntityId;
  providerId: EntityId;
  name: string;
  description?: string;
  durationMinutes: number;
  assignedResourceIds: EntityId[];
  isPublic: boolean;
  paymentPolicy?: SchedulingPaymentPolicy | null;
  notificationPolicy?: SchedulingNotificationPolicy | null;
};
export type AvailabilityRule = { id: EntityId; providerId: EntityId; resourceId: EntityId; timeZoneId: string; daysOfWeek: string[]; localStartTime: string; localEndTime: string };
export type BookableSlot = { providerId: string; serviceId: string; resourceId: string; startsAtUtc: string; endsAtUtc: string; timeZoneId: string; displayLabel: string; providerTimeZoneId: string; displayTimeZoneId: string; displayStartsAtLocal: string; displayEndsAtLocal: string };
export type SchedulingError = { error: string; message: string };
export type HoldResponse = {
  holdId: string;
  claimToken: string;
  expiresAt: string;
  status: string;
  paymentRequirementStatus?: string;
  paymentPolicySnapshot?: SchedulingPaymentPolicy | null;
  paymentReference?: string | null;
  paymentRequiredAt?: string | null;
  paymentSatisfiedAt?: string | null;
};
export type NotificationSummary = { pending: number; sentFake: number; cancelled: number; skipped: number; failed: number; deferredProviderUnavailable: number };
export type ScheduledNotification = {
  id: EntityId;
  providerId: EntityId;
  bookingId: EntityId;
  serviceId: EntityId;
  resourceId: EntityId;
  trigger: string;
  channel: string;
  recipientType: string;
  templateKey: string;
  scheduledForUtc: string;
  status: string;
  linkedOldBookingId?: EntityId | null;
  linkedNewBookingId?: EntityId | null;
  reason?: string | null;
};
export type Booking = {
  id: EntityId;
  providerId?: EntityId;
  serviceId?: EntityId;
  resourceId?: EntityId;
  status: string;
  createdAt?: string;
  updatedAt?: string;
  confirmedAt?: string | null;
  cancelledAt?: string | null;
  customer: { name: string; email: string; phone?: string; notes?: string };
  range?: { startsAtUtc: string; endsAtUtc: string; timeZoneId: string };
  cancellationReasonCode?: string;
  cancellationMessage?: string;
  cancellationActor?: string;
  cancellationPolicyResult?: string;
  paymentStatus?: string;
  paymentRequirementStatus?: string;
  paymentPolicySnapshot?: SchedulingPaymentPolicy | null;
  paymentPolicyLabel?: string;
  paymentReference?: string | null;
  paymentRequiredAt?: string | null;
  paymentSatisfiedAt?: string | null;
  notificationPolicySnapshot?: SchedulingNotificationPolicy | null;
  notificationPolicyLabel?: string;
  notificationSummary?: NotificationSummary;
  rescheduledToBookingId?: string;
  rescheduledFromBookingId?: string;
};
export type BookingAuditEvent = { eventId: string; eventType: string; occurredAt: string; actor?: string; message?: string; data?: Record<string, string> };
export type SchedulingLifecycleSummary = {
  workflowState: string;
  status: string;
  createdAt?: string | null;
  confirmedAt?: string | null;
  cancelledAt?: string | null;
  lastDecisionCode?: string;
  lastAuditEventId?: string;
  checkpointExists?: boolean;
  checkpointPath?: string;
  paymentStatus?: string;
  paymentRequirementStatus?: string;
  paymentReference?: string;
  notificationSummary?: NotificationSummary;
};
export type CancelBookingResponse = { booking: Booking; auditEventId: string; lifecycle: SchedulingLifecycleSummary };
export type SchedulingDispatch = { type: "scheduling.slot-selected"; slot: BookableSlot } | { type: "scheduling.hold-created"; hold: HoldResponse };
